version: '1.0'

services:
  # DEVELOPMENT CONTAINER
  dev:
    container_name: software_ing_api
    image: software-ing-api:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:dev
    ports:
      - "${OUTER_PORT}:${PORT}"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
    networks:
      - software-ing-network
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

# DATABASE CONTAINER
  mongodb:
    image : mongo:latest
    container_name: mongodb
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${DB_DATABASE}
    networks:
      - software-ing-network
    restart: always
    volumes:
      - mongodb_volume:/data/db


# NETWORKS
networks:
    software-ing-network:
      driver: bridge

# VOLUMES
volumes:
  mongodb_volume: